#!/bin/bash

# Create build-directory
mkdir build

# Move into the build-directory
cd build

# Run CMake to create a Makefile
cmake ../

# Make the Makefile using two threads
make -j2

# Move the executable to the top-directory
mv vmc ..
mv importance_sampling ..
mv coulomb_main ..
mv coulomb_importance_sampling ..
